### ISSUE TITLE
Public page not loading properly

### ISSUE THREAD

**Issue by enonied4g** [unicef/drone-4sdgtoolkit#11]
Hello All, 

https://unicef.github.io/drone-4sdgtoolkit/ is not loading properly, there's only plain text displaying instead of the Hugo Theme. 

@jwflory and @Idadelveloper can you help? 

Best!

**Comment by Idadelveloper** [comment]
> Hello All,
> 
> https://unicef.github.io/drone-4sdgtoolkit/ is not loading properly, there's only plain text displaying instead of the Hugo Theme.
> 
> @jwflory and @Idadelveloper can you help?
> 
> Best!

Sure. I suspect it's due to the name change.

**Comment by jwflory** [comment]
This is due to the name change. When the repository name changes, it also changes the URL where GitHub Pages publishes the site. There are two places in the site config (`config.toml`) that also need to be updated for the site to work correctly:

https://github.com/unicef/drone-4sdgtoolkit/blob/16408aeffcf3b318be0496a40659c735ff61436e/config.toml#L1

https://github.com/unicef/drone-4sdgtoolkit/blob/16408aeffcf3b318be0496a40659c735ff61436e/config.toml#L65

Once these are updated, the site should build normally again and appear as expected.
